version: "3.7"

services:
  backend:
    image: bsultana75/ulthit_backend:latest
    command: sh -c "npm start"
    ports:
      - 5000:5000
    volumes:
      - /home/ultimate-hitboxes/server/serverlog:/serverlog
    environment:
      - NODE_ENV=production
      - DB_PW=JY3Z8OvrlWZn
  frontend:
    image: bsultana75/ulthit_frontend:latest
    command: sh -c "yarn build"
    volumes:
      - /home/ultimate-hitboxes/frontend/dist:/dist