version: "3.7"

services:
  backend:
    image: bsultana75/ulthit_backend:latest
    command: sh -c "npm start"
    ports:
      - 5080:5080
      - 5443:5443

    volumes:
      - C:\\Users\\Brandon\\Documents\\ultimate-hitboxes\\server\\data:/data
      - C:\\Users\\Brandon\\Documents\\ultimate-hitboxes\\server\\serverlog:/serverlog
      - C:\\Users\\Brandon\\Documents\\ultimate-hitboxes\\server\\certs:/certs
    environment:
      - NODE_ENV=development
      - DB_PW=JY3Z8OvrlWZn
      - ACCESSKEYID=AKIAQCKJTZIQBQGEPYBH
      - SECRETACCESSKEY=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
      - KEY=/certs/privkey.pem
      - CERT=/certs/fullchain.pem
  frontend:
    image: bsultana75/ulthit_frontend:latest
    command: sh -c "yarn serve"
    ports:
      - 8080:8080
    volumes:
      - C:\\Users\\Brandon\\Documents\\ultimate-hitboxes\\frontend\\src:/src