version: "3.7"

services:
  backend:
    image: bsultana75/ulthit_backend:latest
    command: sh -c "npm start"
    ports:
      - 5000:5000
    volumes:
      - C:\\Users\\Brandon\\Documents\\ultimate-hitboxes\\server\\data:/data
      - C:\\Users\\Brandon\\Documents\\ultimate-hitboxes\\server\\serverlog:/serverlog
    environment:
      - NODE_ENV=development
      - DB_PW=je109DK9XaoL
  frontend:
    image: bsultana75/ulthit_frontend:latest
    command: sh -c "yarn serve"
    ports:
      - 8080:8080
    volumes:
      - C:\\Users\\Brandon\\Documents\\ultimate-hitboxes\\frontend\\src:/src