version: "3.7"

services:
  backend:
    image: bsultana75/ulthit_backend:latest
    command: sh -c "npm start"
    ports:
      - 5080:5080
      - 5443:5443
    volumes:
      - /home/ultimate-hitboxes/server/serverlog:/serverlog
      - /etc/letsencrypt/live/ultimate-hitboxes.com:/certs
    environment:
      - NODE_ENV=production
      - DB_PW=JY3Z8OvrlWZn
  frontend:
    image: bsultana75/ulthit_frontend:latest
    command: sh -c "yarn build"
    volumes:
      - /home/ultimate-hitboxes/frontend/dist:/dist