version: "3.7"

services:
  backend:
    image: bsultana75/ulthit_backend:dev
    command: sh -c "npm start"
    ports:
      - 5000:5000
  frontend:
    image: bsultana75/ulthit_frontend:dev
    command: sh -c "yarn build"
    volumes:
      - C:\\Users\\Brandon\\Documents\\ultimate-hitboxes\\frontend\\dist:/dist